name: painters
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython
  - ipykernel
  - numpy
  - pandas
  - tensorflow
  - scikit-learn
  - matplotlib
  - seaborn
  - hvplot
  - pydot
  - tensorboard
  - pytorch
  - torchvision
  - statsmodels
  - pmdarima
  - prophet
  - pip
  - pip:
    - mlflow
