name: painters
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython
  - ipykernel
  - numpy
  - pandas
  - tensorflow-gpu
  - keras-gpu
  - scikit-learn
  - matplotlib
  - seaborn
  - boto3
  - minio
  - python-dotenv
  - hvplot
  - pydot
  - tensorboard
  - pip
  - pip:
    - mlflow>=1.30.0
    - pylance
    - tensorflow-serving-api
